language: generic
sudo: required
services:
    - docker

before_install:
    - build -t pauloneto94/react-test -f ./client/Dockerfile.dev ./client
    
script:
    - docker run -e CI=true pauloneto94/react-test npm test

after_success:
    - docker build -t pauloneto94/multi-client ./client
    - docker build -t pauloneto94/multi-nginx ./nginx
    - docker build -t pauloneto94/multi-server ./server
    - docker build -t pauloneto94/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push pauloneto94/multi-client
    - docker push pauloneto94/multi-nginx
    - docker push pauloneto94/multi-server
    - docker push pauloneto94/multi-worker        